# Generated by Django 4.2.7 on 2025-09-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_emb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='emb',
        ),
    ]
